# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
       # Runs a single command using the runners shell
      - name: Doxygen Action
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@5636578e966e739b7f06c7fa74b1b3e8267484a5
        uses: mattnotmitt/doxygen-action@1.9.2
        with:
          # Path to Doxyfile
          doxyfile-path: ./docs/Doxyfile
          # Working directory
          working-directory: ./
          # Generate latex documentation
          #enable-latex: # optional

          # Extra alpine packages for the build environment
          #additional-packages: # optional, default is 
      - name: publish report
        uses: mikeal/publish-to-github-action@master
        
        # CKim - Configure token from GitHubRepo-Settings-Secrets-Action-New repository secret
        # below from github page
        env:
          GITHUB_TOKEN: ${{ secrets.THIS_IS_SPARTA }}
          BRANCH_NAME: 'main' # your branch name goes here
